services:
    mongo-db:
        image: mongo:8.0.9
        container_name: mongo-db
        ports:
            - 27017:27017
        volumes:
            - mongodb-data:/data/db
        networks:
            - freelance-network


volumes:
    mongodb-data:

networks:
    freelance-network: